version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    secrets: 
      - db_password_root
      - db_password_user
    environment:
      MYSQL_DATABASE: db_exploits
      MYSQL_ROOT_PASSWORD: ${db_password_root}
      MYSQL_USER: prueba
      MYSQL_USER_PASSWORD: ${db_password_user}
    volumes:
      - ./datos:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 9093:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
  api:
    build: ./api
    container_name: api
    secrets:
      - db_password_root
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${db_password_root}
      DB_DATABASE: db_exploits
      DB_HOST: mysql
      DB_PORT: 3306
      PORT: 8080
      HOST: "0.0.0.0"
    ports: 
      - 9094:8080
    depends_on:
      - mysql
secrets:
  db_password_root:
    file: ./db_password_root
  db_password_user:
    file: ./db_password_user
  